############################################################
# Dockerfile to create a node container to run the project
############################################################
FROM tzenderman/docker-nvm:latest

# Require git for npm install / bower install
RUN apt-get update
RUN apt-get install git -y
RUN apt-get install python -y
RUN apt-get install build-essential -y

# Set working directory
WORKDIR /var/www

# Add user for laravel application
RUN groupadd -g 1001 www
RUN useradd -u 1001 -ms /bin/bash -g www www

COPY /resources/scripts/nvm/entrypoint.sh /entrypoint.sh
COPY /resources/scripts/nvm/image-start-script.sh /image-start-script.sh

CMD [ "/bin/bash", "/entrypoint.sh" ]
