FROM nginx:alpine

COPY /resources/config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /resources/scripts/nginx/entrypoint.sh /docker-scripts/entrypoint.sh

ENTRYPOINT [ "/docker-scripts/entrypoint.sh" ]