############################################################
# Dockerfile to create a node container to run the project
############################################################
FROM node:6

# Set working directory
WORKDIR /var/www

# Add user for laravel application
RUN groupadd -g 1001 www
RUN useradd -u 1001 -ms /bin/bash -g www www

# Change current user to www
USER www

# Expose port 9001 which matches the port node is serving on
EXPOSE 9001