FROM nginx:alpine

RUN mkdir -p /opt/volker

COPY /resources/config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /resources/config/nginx/app.conf /etc/nginx/conf.d/app.conf
COPY /resources/config/nginx/preparing.html /opt/volker/preparing.html

COPY /resources/scripts/nginx/entrypoint.sh /docker-scripts/volker-entrypoint.sh
COPY /resources/scripts/nginx/generate-config.sh /docker-scripts/generate-config.sh

CMD sh /docker-scripts/volker-entrypoint.sh & nginx -g 'daemon off;'