############################################################
# Dockerfile to create a php container to run the project
############################################################

FROM php:7.1-fpm

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev \
    libxml2-dev \
    libyaml-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install mysqli pdo_mysql mbstring zip exif pcntl soap
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install zip gd sockets
RUN docker-php-ext-install opcache
RUN pecl install redis && docker-php-ext-enable redis
RUN pecl install yaml && docker-php-ext-enable yaml

# Copy All Scripts, Configuration Etc
COPY /resources/config/php/ /docker-config/
COPY /resources/scripts/php/ /docker-scripts/

# Run Installation Script
RUN /docker-scripts/install.sh

ENTRYPOINT [ "/entrypoint.sh" ]

# Change to WWW user
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000

CMD ["php-fpm"]

