############################################################
# Dockerfile to create a php container to run the project
############################################################

FROM php:7.1-fpm-bookworm
COPY --from=php:7.1-cli-bookworm /usr/local/bin/phpdbg /usr/local/bin/

# Set working directory
WORKDIR /var/www

# NVM Settings
ENV NVM_DIR /usr/local/nvm
ENV NVM_VERSION v0.39.3

# Copy all config
COPY /resources/config/php/ /docker-config/

# Only copy install scripts
COPY /resources/scripts/php/install_* /docker-scripts/

# Run Installation Scripts
RUN /docker-scripts/install_dependencies.sh
RUN /docker-scripts/install_extensions.sh
RUN /docker-scripts/install_users.sh
RUN /docker-scripts/install_config.sh
RUN /docker-scripts/install_nvm.sh

# Copy Entrypoint & Start Scripts etc.
# If these change we don't want to rerun the above layers, hence do this last.
COPY /resources/scripts/php/entrypoint.sh /docker-scripts/entrypoint.sh
COPY /resources/scripts/php/root-start-script.sh /docker-scripts/root-start-script.sh
COPY /resources/scripts/php/www-start-script.sh /docker-scripts/www-start-script.sh
COPY /resources/scripts/php/qa-start-script.sh /docker-scripts/qa-start-script.sh

# Copy the script to run the scheduler
COPY /resources/scripts/php/run-scheduler.sh /run-scheduler.sh

ENTRYPOINT [ "/docker-scripts/entrypoint.sh" ]

# Change to WWW user
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000

CMD ["php-fpm"]
