############################################################
# Dockerfile to create a php container to run the project
############################################################

FROM php:7.1-fpm

# Set working directory
WORKDIR /var/www

# Copy All Scripts, Configuration Etc
COPY /resources/config/php/ /docker-config/
COPY /resources/scripts/php/ /docker-scripts/

# Run Installation Scripts
RUN /docker-scripts/install_dependencies.sh
RUN /docker-scripts/install_extensions.sh
RUN /docker-scripts/install_users.sh
RUN /docker-scripts/install_config.sh

ENTRYPOINT [ "/docker-scripts/entrypoint.sh" ]

# Change to WWW user
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000

CMD ["php-fpm"]
