name: build-images

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - nginx
          - nginx-cors
          - php-71
          - php-72
          - php-73
          - php-74
          - php-80
          - php-81
          - php-82
          - php-83
          - node-6
          - node-8
          - node-10
          - node-11
          - nvm
          - sync
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.image }}/DockerFile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: rareloop/volker:${{ matrix.image }}
