name: build-nginx

on:
  push:
    branches:
      - 'master'
      - 'feature/ci'

jobs:
  setup-docker:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
  build-nginx:
    needs: setup-docker
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: nginx
          file: nginx/DockerFile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: rareloop/volker:nginx
  build-nginx-cors:
    needs: setup-docker
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: nginx-cors
          file: nginx-cors/DockerFile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: rareloop/volker:nginx-cors